Add Pie Chart Visualization & Update Codebase Structure, Formatting, and Styling
Dollar-Dynasty/finance-app pull request #69
Opened 2024-02-13 15:29 UTC by Scolin022

PR focuses on data visualization, project organization, and UI consistency

- Pie Chart Data-Visualization
Added a basic pie chart using Plotly with mock data for budget categories on the users dashboard
- Global Naming Conventions
Updated all file names to  kebab-case naming convention for consistency and avoiding potential case sensitivity issues.
- File Structures
Updated the organization for JavaScript, CSS, routes, and controller files. This restructuring is for simplifying navigation and to make our code more manageable and adhere to more modern practices of organization.
- Styling Updates
Added some MVP styles for the footer and other minimal aspects of the app. Also added updated to the HTML to add more semantic HTML features: still needs additional work.

2024-02-13 16:14 UTC, dinaolmelak requested changes
I can not accept your PR for the following reasons.
1. There are a lot of commits through this `PR` for me to approve the changes. 
2. Renaming files at this timeline of our project is something I don't agree with.
3. You still have an error.
<img width="1025" alt="Screenshot 2024-02-13 at 10 59 49 in the morning" src="https://github.com/Dollar-Dynasty/finance-app/assets/32272045/b87dbcb6-6d88-4e17-b916-a730db1efd57">
4. You removed the `welcome` page I worked on
5. It's unnecessary to have this line of code if it does not work.
<img width="595" alt="Screenshot 2024-02-13 at 11 04 04 in the morning" src="https://github.com/Dollar-Dynasty/finance-app/assets/32272045/01b89aff-df8c-42bf-a0c3-9e956ed98cb4">
6. Please ask and add the entire team members LinkedIn, not just yours.

There are multiple other small changes that I see that would hinder us from getting more closer to the MVP on this PR. My recommendation is for you to keep this branch locally, close this PR and create another PR from another branch and make the changes which only pertain to your ticket. After we make sure that works, we move forward with other changes.

2024-02-13 16:14 UTC, dinaolmelak commented on views/pages/welcome.ejs
Why did you delete the `welcome` page

2024-02-13 16:19 UTC, Scolin022 commented on views/pages/welcome.ejs
Some clarification:
- I did not delete the welcome page, I just renamed it 'user-dashboard' since it is the dashboard for our app
- Our naming conventions were highly scattered and not consistent, so I updated them to make them consistent. Doing this early on is crucial to avoid a mess later on. If we had a consistent naming convention already in place, this would be a very different story.
<img width="1719" alt="Screenshot 2024-02-13 at 10 19 03 AM" src="https://github.com/Dollar-Dynasty/finance-app/assets/133167499/761fb046-be3d-4fae-9c30-8fdc4800d6b6">

I am not getting an error on my end when I run the branch, It may be a local error.

2024-02-13 17:09 UTC, dinaolmelak commented on views/pages/welcome.ejs
1. It is clear to see that the `welcome` page had been deleted because this thread is under the deletion of the `welcome` page. The following seems more like a dashboard than a welcome page.
![Screenshot 2024-02-13 at 11 49 58 in the morning](https://github.com/Dollar-Dynasty/finance-app/assets/32272045/c3a0207b-1797-4630-a828-3fcdb246de82)
2. I do understand it might be a bad practice to name files and folders in a scattered manner. Trust me I get that 😅, I have had first-hand experience with that with my previous team lol. Nevertheless, we can not make naming changes right now. It is too late for us to change the entire naming convention of our files and folders. It is prone to create bugs. We are also all accustomed to our current naming convention hence it is not a wise decision to make right now. Changing all the naming conventions is another ticket by itself because you have to make sure that the same name is being used everywhere throughout the code.
3. The reason I brought that up is because we will be demoing tomorrow and we do not need any dummy data or placeholders. An MVP should be like the first version that a user could use. 
4. As for the footer it ok, but we currently don't have quote API integrated. Also the content should change if you plan to add it. It should be "Demo Ready"
5. The `develop` branch successfully logs in without any errors and I have seen it work on other team members PC so I doubt it is a localized error
<img width="1023" alt="Screenshot 2024-02-13 at 12 07 49 in the afternoon" src="https://github.com/Dollar-Dynasty/finance-app/assets/32272045/d2a40684-6235-4cac-94cd-fb7c71953e92">

2024-02-13 17:11 UTC, dinaolmelak requested changes
In this PR there had been a lot of changes made.

2024-02-13 17:17 UTC, Scolin022 commented on views/pages/welcome.ejs
- The following seems more like a dashboard than a welcome page because it IS a dashboard. The landing page for a demo for our app is index.ejs, not user-dashboard, which you are seeing in your provided screenshot.
- It is definitely not too late to fix not having a consistent naming convention for our filenames, I even went through the entire app to ensure they all link and work properly despite the name changes.
- The placeholder is a very simple feature and I don't believe would look poorly for an MVP. However, if its a concern, I can work to implement the account users first name being displayed after account creation or login. 
- As for the login feature not being implemented properly, I can definitely do a quick call with you to get that fixed. Besides that bug though, I do not see any interference whatsoever with achieving an MVP with the PR. Let me know if you can here asap to get that fixed!

2024-02-14 01:34 UTC, dinaolmelak approved these changes

2024-02-14 01:34 UTC, dinaolmelak commented on views/script/loginForm.js
are these names going to also change to `Kabab case` naming convention? If so can you quickly change it in your ticket?

2024-02-14 02:15 UTC, bxmtz approved these changes
Went over the changes earlier, great job!

2024-02-14 02:19 UTC, Kendiya242 approved these changes
LGTM.. in future references just make sure let your team know when you make changes next time.

2024-02-14 02:25 UTC, Scolin022 commented
> LGTM.. in future references just make sure let your team know when you make changes next time.

Thats why we do pull requests, so team members can view your changes

2024-02-14 02:26 UTC, nick-talent-sprint commented on views/pages/welcome.ejs
_TL;DR: Quick and dirty good for today (and getting MVP across the finish line tomorrow), then you can put your heads together on how to best clean up._ 

Hey y'all, this **is** a big PR with a lot of changes! However it seems that a Proof of Concept of ejs requires this scale of changes. 

Changing the names *should* ideally be its own ticket. But it's here and almost consistent. 

Semantically `/welcome` is clear, but I'd splash to `my-awesome-app` rather than `my-awesome-app/welcome`. Feels cleaner and easier for the user to remember, but thats opinion.

Add an invented user's name rather than the `{users-name}` placeholder. It seems like a templating error (somebody meant `${users}` or something; that placeholder structure is very similar to a variety of templating tools). Creating a "persona" (1 for MVP, you'd model several in industry) could also be a way for you to speak to your anticipated users' needs. 

Assuming this works checked out on the teams' machines, and lets you demo something tomorrow that wouldn't have happened otherwise, I'd accept it and work on cleaning up inconsistencies later. Spend time together grooming/clarifying the requirements so that this scale of changes is less jarring (or even better, decomposed into several tickets).

2024-02-14 04:05 UTC, merged